# Name of workflow as seen in Github actions tab
name: My FE Project CI Development
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - main
jobs:
  # To build the project
  build-myproject-portal-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.1.1
        with:
          name: "UI deployment started!"
          url: ${{ secrets.SLACK_WEBHOOK }}
          status: ${{ job.status }}

      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Installing dependencies
        run: npm install --legacy-peer-deps

      # - name: Building admin-provider project
      #   run: nx build admin-provider

      # - name: Building patient project
      #   run: nx build patient

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ vars.AWS_REGION_DEV }}

      # - name: Deploy admin-provider to S3 bucket
      #   run: aws s3 sync ./dist/apps/admin-provider s3://${{ secrets.AWS_S3_ADMIN_PROVIDER_BUCKET_DEV }} --delete

      # - name: Deploy patient to S3 bucket
      #   run: aws s3 sync ./dist/apps/patient s3://${{ secrets.AWS_S3_PATIENT_BUCKET_DEV }} --delete

      # - name: Create Admin-Provider invalidation
      #   run: |
      #     distribution_id=${{ secrets.AWS_ADMIN_PROVIDER_CF_DISTRIBUTION_DEV }}
      #     paths='/*'
      #     # Create an invalidation request
      #     invalidation_id=$(aws cloudfront create-invalidation --distribution-id $distribution_id --paths $paths --query 'Invalidation.Id' --output text)
      #     echo "Invalidation request created with ID: $invalidation_id"
      # - name: Create Patient invalidation
      #   run: |
      #     distribution_id=${{ secrets.AWS_PATIENT_CF_DISTRIBUTION_DEV }}
      #     paths='/*'
      #     # Create an invalidation request
      #     invalidation_id=$(aws cloudfront create-invalidation --distribution-id $distribution_id --paths $paths --query 'Invalidation.Id' --output text)
      #     echo "Invalidation request created with ID: $invalidation_id"
      # - name: Chat Setup
      #   uses: Co-qn/google-chat-notification@v1
      #   with:
      #     name: UI deployment completed!
      #     url: ${{ secrets.CHAT_WEBHOOK }}
      #     status: ${{ job.status }}

